version: "3.9"
services:
  ui:
    image: "${EXPENSES_UI_IMAGE}"
    container_name: "expenses-ui"
    ports:
      - "${EXPENSES_UI_PORT}:80"
    networks:
      - default
    env_file:
      - expenses-ui.env
    depends_on:
      backend:
        condition: service_started

networks:
  default:
    driver: bridge
