version: "3.9"
services:
  backend:
    image: "${EXPENSES_BACKEND_IMAGE}"
    container_name: "expenses-backend"
    ports:
      - "${EXPENSES_BACKEND_PORT}:80"
    networks:
      - default
      - expenses-database_default
    env_file:
      - backend.env
    init: true

networks:
  default:
    driver: bridge
  expenses-database_default:
    external: true
